---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

IGNORE_GITIGNORED_FILES: true
DISABLE:
  - COPYPASTE
  - MAKEFILE
DISABLE_LINTERS:
  - COPYPASTE_JSCPD
  - MAKEFILE_CHECKMAKE
  - SPELL_CSPELL
SHOW_ELAPSED_TIME: true
CLEAR_REPORT_FOLDER: true
